In [30]:
import plotly.graph_objects as go
import dash
import numpy as np
import pandas as pd
import dash_core_components as dcc
import dash_html_components as html

from sklearn.datasets import make_blobs
from matplotlib import pyplot
from pandas import DataFrame
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn import svm
import seaborn as sns; sns.set()
%matplotlib inline

In [31]:
X, y= make_blobs(n_samples=100, centers=2, n_features=2)
df = DataFrame(dict(x=X[:,0], y=X[:,1], label=y))
#spliting
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [32]:
X_train

array([[-2.66323745, -4.87471004],
       [-4.83788145, -3.91441753],
       [-5.89734624, -4.69744596],
       [-3.31255969, -4.08745703],
       [-4.01386461, -4.68964576],
       [-4.93861948, -2.23684206],
       [-3.38164753, -5.00380772],
       [-2.51417787, -5.7227175 ],
       [-3.22736893, -4.27707444],
       [-3.23542768, -2.47954925],
       [-5.0407326 , -2.0256376 ],
       [-2.22542933, -5.34517908],
       [-4.32136655, -5.74558352],
       [-6.01187703, -3.47384139],
       [-5.0291129 , -3.78923792],
       [-5.97113696, -3.63939658],
       [-2.51811316, -4.11810238],
       [-4.03841864, -5.35915556],
       [-1.12902222, -4.93596502],
       [-4.62648405, -5.35119894],
       [-2.75298923, -3.67713154],
       [-4.63403648, -6.30162404],
       [-3.63662468, -3.95888303],
       [-1.90942364, -1.75084729],
       [-4.53477164, -3.70486296],
       [-4.41908019, -4.38284408],
       [-6.40032412, -4.34244416],
       [-3.81913645, -3.88968184],
       [-5.43568823,

In [33]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])

In [34]:
X_test

array([[-5.17851954, -4.69709406],
       [-2.43258627, -4.49323209],
       [-3.4529716 , -3.33511306],
       [-2.77277781, -5.91731647],
       [-4.21912995, -4.05573097],
       [-6.32541625, -6.26707047],
       [-4.22586671, -3.19117702],
       [-1.94055682, -4.48818697],
       [-5.35396192, -3.82278343],
       [-3.71347857, -5.33592641],
       [-4.52727059, -4.58532387],
       [-3.33691573, -2.83450132],
       [-3.92725246, -4.3342304 ],
       [-3.26683339, -4.5341901 ],
       [-2.80317069, -4.49275528],
       [-2.85605056, -4.24499215],
       [-2.29061853, -5.40606746],
       [-3.137319  , -4.19510428],
       [-3.62670377, -5.71578982],
       [-4.95454858, -2.96044863]])

In [35]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0])

In [36]:
X_train.shape

(80, 2)

In [37]:
X_test.shape

(20, 2)

In [38]:
y_train.shape

(80,)

In [39]:
y_test.shape

(20,)

In [40]:
fig = px.scatter(df, x=X_train[:,0], y=X_train[:,1],color=y_train)
#fig2 = px.scatter(df, x=X_test[:,0], y=X_test[:,1],color=y_test)
#fig=([fig1 and fig2])

In [41]:
clf = svm.SVC(kernel='linear')

In [42]:
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [43]:
y_pred = clf.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7

In [ ]:
app=dash.Dash()

app.layout=html.Div([
    html.Div(children=[
        html.H1("SVM  VT",style={'color':'red','text-align':'center'})
    ],style={'border':'1px black solid','width':'100%','height':'90px'}),
    html.Div(children=[
        dcc.Graph(id='scatter-plot',
                 figure=fig)
                

    ],style={'border':'1px black solid','float':'center','width':'75%','height':'460px','color':'red'})
])
if __name__=='__main__':
    app.run_server()

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [24/Sep/2021 14:51:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2021 14:51:32] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2021 14:51:32] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2021 14:51:32] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2021 14:51:32] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
